name: helping_hand
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.4
  firebase_auth: ^4.19.6
  firebase_core: ^2.24.2
  firebase_storage: ^11.7.7
  firebase_ui_auth: ^1.14.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_multi_formatter: ^2.12.8
  flutter_password_strength: ^0.1.6
  google_places_autocomplete_text_field: ^0.1.3
  google_places_flutter: ^2.0.8
  http: ^1.2.1
  image_picker: ^1.1.1
  intl_phone_number_input: ^0.7.4
  provider: ^6.0.0
  validation_pro: ^1.1.0

  path: any
  firebase_app_check: ^0.2.2+7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logoHH.png
    - assets/emptyProfilePic.png
    - bruh.env
    - assets/helping-hand-424619-44f804c59d43.json