name: helping_hand
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.4
  firebase_auth: ^4.19.6
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_password_strength: ^0.1.6
  intl_phone_number_input: ^0.7.4
  provider: ^6.0.0
  validation_pro: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logoHH.png
    - assets/emptyProfilePic.png